### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by acwh0110** [PROxZIMA/DarkSpider#29]
I have installed requirements successfully but using Python 3.8 on both on Ubuntu 20.04 and Windows 10 I get the same error after trying to run darkspider.py:

```
Traceback (most recent call last):
  File "darkspider.py", line 58, in <module>
    from modules.helper import get_tor_proxies, setup_custom_logger
  File "/home/acwh0110/DarkSpider/modules/__init__.py", line 1, in <module>
    from modules.crawler import Crawler
  File "/home/acwh0110/DarkSpider/modules/crawler.py", line 15, in <module>
    from modules.checker import url_canon
  File "/home/acwh0110/DarkSpider/modules/checker.py", line 9, in <module>
    from modules.helper import TorProxyException, TorServiceException, get_requests_header
  File "/home/acwh0110/DarkSpider/modules/helper/__init__.py", line 1, in <module>
    from .helper import *
  File "/home/acwh0110/DarkSpider/modules/helper/helper.py", line 79, in <module>
    name: str, filename: str = "log.log", verbose_: bool = False, filelog: bool = True, argv: list[str] = None
TypeError: 'type' object is not subscriptable
```

**Comment by PROxZIMA** [comment]
The type hint `list[str]` is supported in python 3.9 and above. I'll add backward compatibility.
